apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: label-studio
    template: postgresql-persistent-template
  name: label-studio-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
