kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: label-studio
  name: label-studio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem