apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: label-studio
    app.kubernetes.io/component: label-studio
    app.kubernetes.io/instance: label-studio
    app.kubernetes.io/name: label-studio
    app.kubernetes.io/part-of: label-studio
  name: label-studio
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: docker.io/heartexlabs/label-studio:latest
    from:
      kind: DockerImage
      name: docker.io/heartexlabs/label-studio:latest
    name: latest
    referencePolicy:
      type: Local
  - annotations:
      openshift.io/imported-from: docker.io/heartexlabs/label-studio:ubi_latest
    from:
      kind: DockerImage
      name: docker.io/heartexlabs/label-studio:ubi_latest
    name: ubi_latest
    referencePolicy:
      type: Local
