kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/redhat-na-ssa/demo-ocp-label-studio.git'
  name: label-studio
  labels:
    app: label-studio
    app.kubernetes.io/component: label-studio
    app.kubernetes.io/instance: label-studio
    app.kubernetes.io/name: label-studio
    app.kubernetes.io/part-of: label-studio
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'label-studio:s2i'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/redhat-na-ssa/demo-ocp-label-studio.git'
    contextDir: /container
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: label-studio-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: label-studio-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
